package no.ntnu.learniverseconnect.model.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import java.io.Serializable;
import java.sql.Date;

/**
 * Represents a course in the database of the application. Here the values for each course is saved.
 */
@Entity
public class Course implements Serializable {
  /**
   * * <p>id -  an autogenerated ID for each type of course</p>
   * * itle - the title of the level (beginner, intermediate, expert) <br>
   * * diffLevel - int representation of the course (1,2,3)  <br>
   * * closestCourse - the date of the closest course in relation to today's date.  <br>
   * * credits - how many credits this course is worth.  <br>
   * * hoursWeek - how many hours per week this course requires.<br>
   * * relatedCert - related certificates to this course.  <br>
   * * description - the description of the course.  <br>
   * * imgLink - a link to a picture in the server directory representing the course.  <br>
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private long id;
  private String title;
  private int diffLevel;
  private Date closestCourse;
  private float credits;
  private int hoursWeek;
  private String relatedCert;
  @Column(length = 10000)
  private String description;
  private String catergory;
  private String imgLink;

  /**
   * Gets the unique ID of the course.
   *
   * @return the course ID
   */
  public long getId() {
    return id;
  }
  /**
   * Gets the level title of the course.
   *
   * @return the level title
   */
  public String getTitle() {
    return this.title;
  }

  /**
   * Sets the level title of the course.
   *
   * @param levelTitle the level title to set
   */
  public void setTitle(String levelTitle) {
    this.title = levelTitle;
  }

  /**
   * Gets the difficulty level of the course.
   *
   * @return the difficulty level
   */
  public int getDiffLevel() {
    return diffLevel;
  }

  /**
   * Sets the difficulty level of the course.
   *
   * @param diffLevel the difficulty level to set
   */
  public void setDiffLevel(int diffLevel) {
    this.diffLevel = diffLevel;
  }

  /**
   * Gets the date of the closest course.
   *
   * @return the closest course date
   */
  public Date getClosestCourse() {
    return closestCourse;
  }

  /**
   * Sets the date of the closest course.
   *
   * @param closestCourse the closest course date to set
   */
  public void setClosestCourse(Date closestCourse) {
    this.closestCourse = closestCourse;
  }

  /**
   * Gets the credits of the course.
   *
   * @return the credits
   */
  public float getCredits() {
    return credits;
  }

  /**
   * Sets the credits of the course.
   *
   * @param credits the credits to set
   */
  public void setCredits(float credits) {
    this.credits = credits;
  }

  /**
   * Gets the hours per week required for the course.
   *
   * @return the hours per week
   */
  public int getHoursWeek() {
    return hoursWeek;
  }

  /**
   * Sets the hours per week required for the course.
   *
   * @param hoursWeek the hours per week to set
   */
  public void setHoursWeek(int hoursWeek) {
    this.hoursWeek = hoursWeek;
  }

  /**
   * Gets the related certificates of the course.
   *
   * @return the related certificates
   */
  public String getRelatedCert() {
    return relatedCert;
  }

  /**
   * Sets the related certificates of the course.
   *
   * @param relatedCert the related certificates to set
   */
  public void setRelatedCert(String relatedCert) {
    this.relatedCert = relatedCert;
  }

  /**
   * Gets the description of the course.
   *
   * @return the description
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the description of the course.
   *
   * @param description the description to set
   */
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * Gets the image link of the course.
   *
   * @return the image link
   */
  public String getImgLink() {
    return imgLink;
  }

  /**
   * Sets the image link of the course.
   *
   * @param imgLink the image link to set
   */
  public void setImgLink(String imgLink) {
    this.imgLink = imgLink;
  }

  /**
   * Get the category this course belongs to.
   *
   * @return the category this course belongs to.
   */
  public String getCatergory() {
    return catergory;
  }

  /**
   * Set the category this course belongs to.
   *
   * @param catergory the category to set.
   */

  public void setCatergory(String catergory) {
    this.catergory = catergory;
  }
}
